name: Rust Build and Optimize

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build optimized binary
      run: cargo build --release
      working-directory: my_project  # Specify the subdirectory here

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_project_binary
        path: my_project/target/release/
      working-directory: my_project  # Specify the subdirectory here
